Add test cases for SecResponseBodyLimit
Test results:
```
$ go test -v -run TestLongResponseBody
=== RUN   TestLongResponseBody
=== RUN   TestLongResponseBody/EqualToLimit
2025/10/02 08:25:04.056 INFO    using config from file  {"file": "/tmp/2500147150"}
2025/10/02 08:25:04.056 INFO    adapted config to JSON  {"adapter": "caddyfile"}
2025/10/02 08:25:04.056 INFO    admin   admin endpoint started  {"address": "localhost:2999", "enforce_origin": false, "origins": ["//localhost:2999", "//[::1]:2999", "//127.0.0.1:2999"]}
2025/10/02 08:25:04.056 INFO    autosaved config (load with --resume flag)      {"file": "/home/hnakamur/.config/caddy/autosave.json"}
2025/10/02 08:25:04.056 INFO    serving initial configuration
2025/10/02 08:25:05.057 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35438", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.057 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35452", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.058 INFO    admin.api       received request        {"method": "POST", "host": "localhost:2999", "uri": "/load", "remote_ip": "127.0.0.1", "remote_port": "35462", "headers": {"Accept-Encoding":["gzip"],"Content-Length":["380"],"Content-Type":["text/caddyfile"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.059 INFO    admin   admin endpoint started  {"address": "localhost:2999", "enforce_origin": false, "origins": ["//localhost:2999", "//[::1]:2999", "//127.0.0.1:2999"]}
2025/10/02 08:25:05.060 INFO    http.auto_https automatic HTTPS is completely disabled for server       {"server_name": "srv0"}
2025/10/02 08:25:05.060 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0003ae180"}
2025/10/02 08:25:05.060 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":34401"}
2025/10/02 08:25:05.060 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":34401"}
2025/10/02 08:25:05.060 INFO    http.log        server running  {"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2025/10/02 08:25:05.060 INFO    autosaved config (load with --resume flag)      {"file": "/home/hnakamur/.config/caddy/autosave.json"}
2025/10/02 08:25:05.060 INFO    admin.api       load complete
2025/10/02 08:25:05.060 INFO    [INFO][FileStorage:/home/hnakamur/.local/share/caddy] Lock for 'storage_clean' is stale (created: 2025-10-02 17:24:37.557711766 +0900 JST, last update: 2025-10-02 17:24:37.557711766 +0900 JST); removing then retrying: /home/hnakamur/.local/share/caddy/locks/storage_clean.lock
2025/10/02 08:25:05.060 INFO    caddytest: config load time took 2.429539ms
2025/10/02 08:25:05.061 INFO    admin   stopped previous server {"address": "localhost:2999"}
2025/10/02 08:25:05.061 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35464", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.061 INFO    tls     storage cleaning happened too recently; skipping for now        {"storage": "FileStorage:/home/hnakamur/.local/share/caddy", "instance": "eec4e826-e075-40d5-a6c6-51f9bbfd2e65", "try_again": "2025/10/03 08:25:05.061", "try_again_in": 86399.99999934}
2025/10/02 08:25:05.061 INFO    tls     finished cleaning storage units
2025/10/02 08:25:05.061 INFO    caddytest: redirecting the dialer from 127.0.0.1:34401 to 127.0.0.1:34401
=== RUN   TestLongResponseBody/OneByteLongerThanLimit
2025/10/02 08:25:05.063 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35468", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.064 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35482", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.065 INFO    admin.api       received request        {"method": "POST", "host": "localhost:2999", "uri": "/load", "remote_ip": "127.0.0.1", "remote_port": "35496", "headers": {"Accept-Encoding":["gzip"],"Content-Length":["380"],"Content-Type":["text/caddyfile"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.066 INFO    admin   admin endpoint started  {"address": "localhost:2999", "enforce_origin": false, "origins": ["//localhost:2999", "//[::1]:2999", "//127.0.0.1:2999"]}
2025/10/02 08:25:05.066 INFO    http.auto_https automatic HTTPS is completely disabled for server       {"server_name": "srv0"}
2025/10/02 08:25:05.067 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":46435"}
2025/10/02 08:25:05.067 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":46435"}
2025/10/02 08:25:05.067 INFO    http.log        server running  {"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2025/10/02 08:25:05.067 INFO    http    servers shutting down with eternal grace period
2025/10/02 08:25:05.067 INFO    autosaved config (load with --resume flag)      {"file": "/home/hnakamur/.config/caddy/autosave.json"}
2025/10/02 08:25:05.067 INFO    admin.api       load complete
2025/10/02 08:25:05.067 INFO    caddytest: config load time took 2.726391ms
2025/10/02 08:25:05.068 INFO    admin   stopped previous server {"address": "localhost:2999"}
2025/10/02 08:25:05.068 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35506", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 08:25:05.069 INFO    caddytest: redirecting the dialer from 127.0.0.1:46435 to 127.0.0.1:46435
2025/10/02 08:25:05.070 WARN    http.handlers.reverse_proxy     aborting with incomplete response       {"upstream": "127.0.0.1:41727", "duration": 0.000395675, "request": {"remote_ip": "127.0.0.1", "remote_port": "39586", "client_ip": "127.0.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1:46435", "uri": "/", "headers": {"User-Agent": ["Go-http-client/1.1"], "Accept-Encoding": ["gzip"], "X-Forwarded-For": ["127.0.0.1"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Host": ["127.0.0.1:46435"]}}, "error": "short write"}
    caddytest.go:480: failed to call server Get "http://127.0.0.1:46435": EOF
2025/10/02 08:25:05.070 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "35506", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
    caddytest.go:134: ----------- failed with config -----------
        {
          "admin": {
            "listen": "localhost:2999"
          },
          "apps": {
            "http": {
              "servers": {
                "srv0": {
                  "automatic_https": {
                    "disable": true
                  },
                  "listen": [
                    ":46435"
                  ],
                  "routes": [
                    {
                      "handle": [
                        {
                          "directives": "\n\t\t\t\t\t\tSecRuleEngine On\n\t\t\t\t\t\tSecResponseBodyAccess On\n\t\t\t\t\t\tSecResponseBodyMimeType text/plain\n\t\t\t\t\t\tSecResponseBodyLimit 64\n\t\t\t\t\t\tSecResponseBodyLimitAction ProcessPartial\n\t\t\t\t\t",
                          "handler": "waf",
                          "include": [],
                          "load_owasp_crs": false
                        },
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [
                            {
                              "dial": "127.0.0.1:41727"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
--- FAIL: TestLongResponseBody (1.02s)
    --- PASS: TestLongResponseBody/EqualToLimit (1.01s)
    --- FAIL: TestLongResponseBody/OneByteLongerThanLimit (0.01s)
FAIL
exit status 1
FAIL    github.com/corazawaf/coraza-caddy/v2    1.038s
```

The "aborting with incomplete response" erorr is returned at:
https://github.com/caddyserver/caddy/blob/v2.9.1/modules/caddyhttp/reverseproxy/reverseproxy.go#L1066-L1068

The "short write" error is returned at:
https://github.com/caddyserver/caddy/blob/v2.9.1/modules/caddyhttp/reverseproxy/streaming.go#L358

The short write is caused at:
https://github.com/corazawaf/coraza/blob/v3.3.3/internal/corazawaf/transaction.go#L1158