Add test cases for SecResponseBodyLimitAction Reject
Test results:
```
~/ghq/github.com/corazawaf/coraza-caddy$ go test -v -run TestLongResponseBody
=== RUN   TestLongResponseBody
=== RUN   TestLongResponseBody/EqualToLimit_ProcessPartial
2025/10/02 09:00:57.309 INFO    using config from file  {"file": "/tmp/3419700223"}
2025/10/02 09:00:57.309 INFO    adapted config to JSON  {"adapter": "caddyfile"}
2025/10/02 09:00:57.309 INFO    admin   admin endpoint started  {"address": "localhost:2999", "enforce_origin": false, "origins": ["//localhost:2999", "//[::1]:2999", "//127.0.0.1:2999"]}
2025/10/02 09:00:57.309 INFO    autosaved config (load with --resume flag)      {"file": "/home/hnakamur/.config/caddy/autosave.json"}
2025/10/02 09:00:57.309 INFO    serving initial configuration
2025/10/02 09:00:58.310 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "57080", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 09:00:58.312 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2999", "uri": "/config/", "remote_ip": "127.0.0.1", "remote_port": "57084", "headers": {"Accept-Encoding":["gzip"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 09:00:58.313 INFO    admin.api       received request        {"method": "POST", "host": "localhost:2999", "uri": "/load", "remote_ip": "127.0.0.1", "remote_port": "57096", "headers": {"Accept-Encoding":["gzip"],"Content-Length":["412"],"Content-Type":["text/caddyfile"],"User-Agent":["Go-http-client/1.1"]}}
2025/10/02 09:00:58.316 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":46535"}
2025/10/02 09:00:58.316 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":46535"}
2025/10/02 09:00:58.317 INFO    caddytest: config load time took 4.667624ms
2025/10/02 09:00:58.319 INFO    caddytest: redirecting the dialer from 127.0.0.1:46535 to 127.0.0.1:46535
=== RUN   TestLongResponseBody/OneByteLongerThanLimit_ProcessPartial
2025/10/02 09:00:58.321 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":38367"}
2025/10/02 09:00:58.321 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":38367"}
2025/10/02 09:00:58.321 INFO    caddytest: config load time took 745.612µs
2025/10/02 09:00:58.322 INFO    caddytest: redirecting the dialer from 127.0.0.1:38367 to 127.0.0.1:38367
2025/10/02 09:00:58.322 WARN    http.handlers.reverse_proxy     aborting with incomplete response       {"upstream": "127.0.0.1:39687", "duration": 0.000082412, "request": {"remote_ip": "127.0.0.1", "remote_port": "43650", "client_ip": "127.0.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "127.0.0.1:38367", "uri": "/", "headers": {"X-Forwarded-Proto": ["http"], "X-Forwarded-Host": ["127.0.0.1:38367"], "User-Agent": ["Go-http-client/1.1"], "Accept-Encoding": ["gzip"], "X-Forwarded-For": ["127.0.0.1"]}}, "error": "short write"}
    caddytest.go:480: failed to call server Get "http://127.0.0.1:38367": EOF
    caddytest.go:134: ----------- failed with config -----------
        {
          "admin": {
            "listen": "localhost:2999"
          },
          "apps": {
            "http": {
              "servers": {
                "srv0": {
                  "automatic_https": {
                    "disable": true
                  },
                  "listen": [
                    ":38367"
                  ],
                  "routes": [
                    {
                      "handle": [
                        {
                          "directives": "\n\t\t\t\t\t\tSecRuleEngine On\n\t\t\t\t\t\tSecResponseBodyAccess On\n\t\t\t\t\t\tSecResponseBodyMimeType text/plain\n\t\t\t\t\t\tSecResponseBodyLimit 64\n\t\t\t\t\t\tSecResponseBodyLimitAction ProcessPartial\n\t\t\t\t\t",
                          "handler": "waf",
                          "include": [],
                          "load_owasp_crs": false
                        },
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [
                            {
                              "dial": "127.0.0.1:39687"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              }
            }
          },
          "logging": {
            "logs": {
              "default": {
                "level": "WARN"
              }
            }
          }
        }
=== RUN   TestLongResponseBody/EqualToLimit_Reject
2025/10/02 09:00:58.326 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":37299"}
2025/10/02 09:00:58.326 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":37299"}
2025/10/02 09:00:58.326 INFO    caddytest: config load time took 2.117858ms
2025/10/02 09:00:58.328 INFO    caddytest: redirecting the dialer from 127.0.0.1:37299 to 127.0.0.1:37299
2025/10/02 09:00:58.329 WARN    http.handlers.waf       Disrupting transaction with body size above the configured limit (Action Reject)        {"tx_id": "STzSKHHSZrMTacIt"}
=== RUN   TestLongResponseBody/OneByteLongerThanLimit_Reject
2025/10/02 09:00:58.331 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":38685"}
2025/10/02 09:00:58.331 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":38685"}
2025/10/02 09:00:58.331 INFO    caddytest: config load time took 1.10458ms
2025/10/02 09:00:58.331 INFO    caddytest: redirecting the dialer from 127.0.0.1:38685 to 127.0.0.1:38685
2025/10/02 09:00:58.332 WARN    http.handlers.waf       Disrupting transaction with body size above the configured limit (Action Reject)        {"tx_id": "nwEUrGCuvnZoyMaL"}
=== RUN   TestLongResponseBody/OneByteShorterThanLimit_Reject
2025/10/02 09:00:58.333 WARN    http    HTTP/2 skipped because it requires TLS  {"network": "tcp", "addr": ":43985"}
2025/10/02 09:00:58.333 WARN    http    HTTP/3 skipped because it requires TLS  {"network": "tcp", "addr": ":43985"}
2025/10/02 09:00:58.333 INFO    caddytest: config load time took 878.502µs
2025/10/02 09:00:58.334 INFO    caddytest: redirecting the dialer from 127.0.0.1:43985 to 127.0.0.1:43985
--- FAIL: TestLongResponseBody (1.03s)
    --- PASS: TestLongResponseBody/EqualToLimit_ProcessPartial (1.01s)
    --- FAIL: TestLongResponseBody/OneByteLongerThanLimit_ProcessPartial (0.00s)
    --- PASS: TestLongResponseBody/EqualToLimit_Reject (0.01s)
    --- PASS: TestLongResponseBody/OneByteLongerThanLimit_Reject (0.00s)
    --- PASS: TestLongResponseBody/OneByteShorterThanLimit_Reject (0.00s)
FAIL
exit status 1
FAIL    github.com/corazawaf/coraza-caddy/v2    1.046s
```